server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.133.11
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.133.11:3306/guli_cart
    username: root
    password: 123456
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.133.11
    virtual-host: /canglx
    username: canglx
    password: canglx
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
auth:
  jwt:
    pubKeyPath: D:\\project\\rsa\\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
    expireTime: 15552000 # userKey的过期时间