server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route # 搜索管理路由
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: index-route # 搜索管理路由
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com, gmall.com, index.gmall.com
          filters:
            - Auth=/
        - id: index-route2 # 首页的异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route # 商品详情路由
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route # 授权管理
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com


      x-forwarded:
        host-enabled: true
auth:
  jwt:
    pubKeyPath: D:\\project\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL-TOKEN