server:
  port: 18081
spring:
  rabbitmq:
    host: 192.168.133.11
    port: 5672
    virtual-host: /canglx
    username: canglx
    password: canglx
    publisher-confirm-type: simple # SIMPLE-同步确认（阻塞） CORRELATED-异步确认
    publisher-returns: true # 确认消息是否到达队列
feign:
  sentinel:
    enabled: true
# 映射文件地址
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml
  # 别名扫描包
  type-aliases-package: com.atguigu.gmall.pms.entity
  # id的生成策略
  global-config:
    db-config:
      id-type: auto