server:
  port: 18085



feign:
  sentinel:
    enabled: true
# 映射文件地址
mybatis-plus:
  mapper-locations: classpath:mapper/wms/*.xml
  # 别名扫描包
  type-aliases-package: com.atguigu.gmall.wms.entity
  # id的生成策略
  global-config:
    db-config:
      id-type: auto
